### ISSUE TITLE
Redwood V8 upgrade breaks stripe 

### ISSUE THREAD

**Issue by shansmith01** [chrisvdm/redwoodjs-stripe#142]
Hi There,

Upgrading to v8 is producing an error as follows

Error
You must register a useMutation hook via the `GraphQLHooksProvider`
@fs//node_modules/@redwoodjs/web/dist/cjs/components/GraphQLHooksProvider.js in Object.useMutation
45      "You must register a useQuery hook via the `GraphQLHooksProvider`"
46    );
47  },
48  useMutation: () => {
49    throw new Error(
50      "You must register a useMutation hook via the `GraphQLHooksProvider`"
51    );
52  },
53  useSubscription: () => {
54    throw new Error(
[@fs//node_modules/@redwoodjs/web/dist/cjs/components/GraphQLHooksProvider.js in useMutation2](vscode://file/@fs//node_modules/@redwoodjs/web/dist/cjs/components/GraphQLHooksProvider.js:106:63)
[@fs//node_modules/@redwoodjs-stripe/web/dist/cjs/hooks/useStripeCheckout.js in useStripeCheckout](vscode://file/@fs//node_modules/@redwoodjs-stripe/web/dist/cjs/hooks/useStripeCheckout.js:39:37)
[pages/BuyPage/BuyPage.tsx in BuyPageForm](vscode://file/pages/BuyPage/BuyPage.tsx:22:24)
[@fs//node_modules/scheduler/cjs/scheduler.development.js in workLoop](vscode://file/@fs//node_modules/scheduler/cjs/scheduler.development.js:266:34)
[@fs//node_modules/scheduler/cjs/scheduler.development.js in flushWork](vscode://file/@fs//node_modules/scheduler/cjs/scheduler.development.js:239:14)
[@fs//node_modules/scheduler/cjs/scheduler.development.js in MessagePort.performWorkUntilDeadline](vscode://file/@fs//node_modules/scheduler/cjs/scheduler.development.js:533:21)

Does the rw stripe package need an upgrade?

**Comment by shansmith01** [comment]
Minimal repo here https://github.com/shansmith01/rw-stripe-1

Navigate to http://localhost:8910/stripe-demo

error is 

..../rw-stripe/node_modules/@redwoodjs/web/dist/cjs/components/GraphQLHooksProvider.js in Object.useQuery
40module.exports = __toCommonJS(GraphQLHooksProvider_exports);
41var import_react = __toESM(require("react"), 1);
42const GraphQLHooksContext = import_react.default.createContext({
43  useQuery: () => {
44    throw new Error(
45      "You must register a useQuery hook via the `GraphQLHooksProvider`"
46    );
47  },
48  useMutation: () => {
49    throw new Error(...

[@fs/.../Dev/rw-stripe/node_modules/@redwoodjs/web/dist/cjs/components/GraphQLHooksProvider.js in useQuery2](vscode://file/@fs/.../Dev/rw-stripe/node_modules/@redwoodjs/web/dist/cjs/components/GraphQLHooksProvider.js:100:63)
[@fs/.../Dev/rw-stripe/node_modules/@redwoodjs-stripe/web/dist/cjs/hooks/useStripeCustomerPortal.js in useStripeCustomerPortal](vscode://file/@fs/.../Dev/rw-stripe/node_modules/@redwoodjs-stripe/web/dist/cjs/hooks/useStripeCustomerPortal.js:53:61)
[pages/StripeDemoPage/StripeDemoPage.tsx in StripeCustomerPortalButton](vscode://file/pages/StripeDemoPage/StripeDemoPage.tsx:106:7)

All data still seems to come through in the response

**Comment by chrisvdm** [comment]
Just released now
v1.0.10
