### ISSUE TITLE
Example Store

### ISSUE THREAD

**Issue by chrisvdm** [chrisvdm/redwoodjs-stripe#4]
Build an example Store to demonstrate the power of Stripe and Redwood together and also tackle the plugin from a different direction.

This task is being worked on in the following repo:
[Example Store](https://github.com/redwoodjs/example-store)

**Comment by chrisvdm** [comment]
@adriatic Thank you! Anything you could do would be greatly appreciated. 

Yeah, I understand the ETA is very close... it's more of a guide for now, but yeah thank you so much for jumping in :)

**Comment by adriatic** [comment]
Hello @chrisvdm I was already interested in RW - Stripe integration, so it was a lucky incident that I found your project and realized that by helping you I may get the best start on RW+Stripe.

Two questions: 
1. Is the [example store](https://github.com/chrisvdm/redwoodjs-stripe) repository current (can I just clone it and start working on your [issues](https://github.com/chrisvdm/redwoodjs-stripe/issues) ?

2. Can you please tell me the where to start (from the viewpoint of helping the most important stuff first) -- or should I just pick anything from the [list of issues](https://github.com/chrisvdm/redwoodjs-stripe/issues)?

**Comment by adriatic** [comment]
@chrisvdm @jtoar

I was (incorrectly) assuming that we will have the opportunity to answer each other's questions at least once a day. As this was not possible, I had some quality interactions with Stripe support team members and have resolved the issue that this [README](https://github.com/redwoodjs/example-store-stripe#stripe-superstore) is behind the Stripe UX.

So, before I create any PR, I will establish the correlation between your [README](https://github.com/redwoodjs/example-store-stripe#stripe-superstore) and today's [Stripe documentation](https://stripe.com/docs/development).

As an example, the developer's keys are not on the [Dashboard](https://dashboard.stripe.com/test/dashboard) - but rather in my own personalized page:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/2712405/171233592-7f63ab7e-ca20-49e7-8e7d-4f1ce67a346d.png">

While going through this documentation I will not try do anything about your existing issues, it would be too risky by my opinion.

**Comment by chrisvdm** [comment]
@adriatic Thank you for jumping on the README. That really helps out a  lot. As I am moving towards working solely on the plugin I do need help with maintaining/squashing bugs with the example store. So anything you can do over there would be awesome. 

With the plugin repo I still have to think of the best ways to make use of contributors, but for now you can jump in wherever you see the "contributors welcome" label. At the moment there isn't any but there will be soon.

Myself and @tjoar are on very different parts of the planet and work weird times, so it might not always be possible to get back to you on the day 

Again I really appreciate you wanting to be so involved :)
