### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by edmondecad** [chrisvdm/redwoodjs-stripe#66]
Hello, I am trying to use this for a RedwoodJS Typescript project but I am running into a few errors. 

The first issue was that the `StripeItemsParamsInput` type was unknown. 
- I copied the `stripeItem.sdl.ts` and `customerPortal.sdl.ts` and got that working. 

But now my GraphQL query returns null for the query below.
```
export const QUERY = gql`
  query StripeItems($params: StripeItemsParamsInput) {
    stripeItems(params: $params) {
      id
      name
      description
      images
      price
      type
    }
  }
`
```

This only happens when in the Redwood Typescript app. When I try this in a Redwood Javascript app, it works fine with the same Stripe account. 

One difference I noticed was that the Javascript app has the following in `graphql.js` while the Typescript app doesn't. I'm not sure if this is whats causing it. I did not do anything other than the installation instructions and adding the two SDL files above.

Thank you for your time.

**Comment by tomjdickson** [comment]
I believe once the SDL file is defined in your project it's expecting a service to relate to it within your project and not "stripeServices". Hence why your query won't be working.

Not sure how we can resolve this at the moment, I am assuming in a production environment you'll probably end up building your own query and input types anyway.
