### ISSUE TITLE
GraphQL schema exposes customer data

### ISSUE THREAD

**Issue by Benjamin-Lee** [chrisvdm/redwoodjs-stripe#94]
<img width="1238" alt="image" src="https://github.com/chrisvdm/redwoodjs-stripe/assets/13618205/3bfc1761-a301-418e-ab64-f89a808be431">

Nothing critical seems to be exposed but perhaps this should be locked down. There are lots of use cases where you don't want to leak the emails of purchasers.

**Comment by chrisvdm** [comment]
@Benjamin-Lee  Thank you for catching this 🚀 

Had a few rogue skipAuth directives from early development days to make testing easier :)
